### ISSUE TITLE
Resolutions are not generated (or even detected) on some assets

### ISSUE THREAD

**Issue by agajdosi** [BlenderKit/blenderkit_asset_tasks#7] opened 2024-01-26 10:06 UTC
Example: Cashew Nut (https://www.blenderkit.com/asset-gallery-detail/4fa582f9-97f9-4c9d-8072-cc37b5a439b2/)

```
downloading and generating resolution for  Cashew Nut
getting download url
{'fileType': 'blend', 'downloadUrl': 'https://www.blenderkit.com/api/v1/downloads/301438/', 'fileThumbnail': None, 'fileThumbnailLarge': None, 'created': '2024-01-22T02:49:13.207998+01:00', 'modified': '2024-01-22T02:49:13.208017+01:00', 'mimeType': None, 'resolution': None}
200 {"fileType":"blend","uuid":"8a5e4eb9-5d19-47cc-9963-5fa0c310de48","filePath":"https://public.blenderkit.com/public-assets/assets/1b4af472e9714e25a1b6d5afd8c3e795/files/blend_34eb6d63-c88e-480d-becd-42e92222bea7.blend"}
URL: https://public.blenderkit.com/public-assets/assets/1b4af472e9714e25a1b6d5afd8c3e795/files/blend_34eb6d63-c88e-480d-becd-42e92222bea7.blend
file paths ['/tmp/cashew_nut_1b4af472-e971-4e25-a1b6-d5afd8c3e795/cashew_nut_34eb6d63-c88e-480d-becd-42e92222bea7.blend']
file paths ['/tmp/cashew_nut_1b4af472-e971-4e25-a1b6-d5afd8c3e795/cashew_nut_34eb6d63-c88e-480d-becd-42e92222bea7.blend']
check if file already exists['/tmp/cashew_nut_1b4af472-e971-4e25-a1b6-d5afd8c3e795/cashew_nut_34eb6d63-c88e-480d-becd-42e92222bea7.blend']
Downloading /tmp/cashew_nut_1b4af472-e971-4e25-a1b6-d5afd8c3e795/cashew_nut_34eb6d63-c88e-480d-becd-42e92222bea7.blend
Downloading Cashew Nut 3.7MB 1% 
Downloading Cashew Nut 3.7MB 2% 
Downloading Cashew Nut 3.7MB 3% 
Downloading Cashew Nut 3.7MB 4% 
Downloading Cashew Nut 3.7MB 5% 
Downloading Cashew Nut 3.7MB 6% 
Downloading Cashew Nut 3.7MB 7% 
Downloading Cashew Nut 3.7MB 8% 
Downloading Cashew Nut 3.7MB 9% 
Downloading Cashew Nut 3.7MB 10% 
Downloading Cashew Nut 3.7MB 11% 
Downloading Cashew Nut 3.7MB 12% 
Downloading Cashew Nut 3.7MB 13% 
Downloading Cashew Nut 3.7MB 14% 
Downloading Cashew Nut 3.7MB 15% 
Downloading Cashew Nut 3.7MB 16% 
Downloading Cashew Nut 3.7MB 17% 
Downloading Cashew Nut 3.7MB 19% 
Downloading Cashew Nut 3.7MB 20% 
Downloading Cashew Nut 3.7MB 21% 
Downloading Cashew Nut 3.7MB 22% 
Downloading Cashew Nut 3.7MB 23% 
Downloading Cashew Nut 3.7MB 24% 
Downloading Cashew Nut 3.7MB 25% 
Downloading Cashew Nut 3.7MB 26% 
Downloading Cashew Nut 3.7MB 27% 
Downloading Cashew Nut 3.7MB 28% 
Downloading Cashew Nut 3.7MB 82% 
Downloading Cashew Nut 3.7MB 83% 
Downloading Cashew Nut 3.7MB 84% 
Downloading Cashew Nut 3.7MB 85% 
Downloading Cashew Nut 3.7MB 86% 
Downloading Cashew Nut 3.7MB 87% 
Downloading Cashew Nut 3.7MB 88% 
Downloading Cashew Nut 3.7MB 89% 
Downloading Cashew Nut 3.7MB 90% 
Downloading Cashew Nut 3.7MB 91% 
Downloading Cashew Nut 3.7MB 92% 
Downloading Cashew Nut 3.7MB 94% 
Downloading Cashew Nut 3.7MB 95% 
Downloading Cashew Nut 3.7MB 96% 
Downloading Cashew Nut 3.7MB 97% 
Downloading Cashew Nut 3.7MB 98% 
Downloading Cashew Nut 3.7MB 99% 
Downloading Cashew Nut 3.7MB 100% 
asset blender version 4.0002
('4', '0')
asset blender version from blend 4.0
asset blender version picked 4.0002
(3.06, '3.6')
/home/headless/blenders/3.6/blender
opening Blender instance to do processing -  unpack_asset_bg.py
STDOUT: Blender 3.6.8 (hash f6ae60f3eeda built 2024-01-16 00:32:28)
STDOUT: Read blend: "/tmp/cashew_nut_1b4af472-e971-4e25-a1b6-d5afd8c3e795/cashew_nut_34eb6d63-c88e-480d-becd-42e92222bea7.blend"
STDOUT: Warning: region type 14 missing in space type "View3D" (id: 1) - removing region
STDOUT: Warning: region type 15 missing in space type "View3D" (id: 1) - removing region
STDOUT: Warning: File written by newer Blender binary (400.36), expect loss of data!
STDOUT: background asset unpack
STDOUT: Info: Saved "cashew_nut_34eb6d63-c88e-480d-becd-42e92222bea7.blend"
asset blender version 4.0002
('3', '6')
asset blender version from blend 3.6
asset blender version picked 4.0002
(3.06, '3.6')
/home/headless/blenders/3.6/blender
opening Blender instance to do processing -  resolutions_bg_blender.py
STDOUT: background resolution generator
STDOUT: current resolution of the asset  0
STDOUT: Blender 3.6.8 (hash f6ae60f3eeda built 2024-01-16 00:32:28)
STDOUT: Read blend: "/tmp/cashew_nut_1b4af472-e971-4e25-a1b6-d5afd8c3e795/cashew_nut_34eb6d63-c88e-480d-becd-42e92222bea7.blend"
STDOUT: 
STDOUT: Blender quit
result state: skipped
changing asset variable
patching asset with empty data
patched asset with empty data
deleting temp folder
deleted temp folder
```

Please take a look @vilemduha. I expect this asset does not have texture? If so, this is not a bug, but we need to solve a problem - how to detect it, so these assets are not fetched during the nightly job? Is there any parameter for this?

**Comment by vilemduha** [comment] 2024-06-19 15:13
The example asset in this issue is procedural , and I think it's a duplicate of issue #160
https://github.com/BlenderKit/blenderkit-team-work/issues/160

So I'm closing this one.

**Closed by vilemduha** 2024-06-19 15:13 UTC
